permalink: /:categories/:title.html
url: "http://smaolab.github.io/"
full_name: "SMAO LAB"
first_name: "SMAO"
last_name: "LAB"
blog_title: "SMAO LAB"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "smaolab"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: ""
github: "smaolab"
facebook: ""
linkined_url: ""
