# Site settings

title: SMAO LAB
tagline: "Electro music and more"

repository_url: "https://github.com/Smaolab/smaolab"
master_raw: "https://github.com/Smaolab/smaolab/tree/master"
wiki_url: "https://github.com/Smaolab/smaolab/wiki"

email: egnouf@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  SMAO LAB.....

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://smaolab.github.io" # the base hostname & protocol for your site


twitter_username: stephaneribas
github_username:  rstephane

# Build settings
markdown: kramdown
# Keep the same markdown on Github
kramdown:
  input: GFM
