permalink: /:categories/:title.html
url: "http://smaolab.github.io/"
full_name: "SMAO LAB"
first_name: "SMAO"
last_name: "LAB"
blog_title: "SMAO LAB"
author_img_name_path: "/images/users/user.jpg"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Electro music and more"
twitter: ""
github: "smaolab"
